### ISSUE TITLE
Chaining two webhook interceptors breaks the output of the first

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#973]
# Expected Behavior

I can use two or more webhook interceptors one after the other.

# Actual Behavior

The output of the first webhook interceptor appears to be deleted by the execution of the second interceptor.
The issue seems to happen only when the two webhook interceptors are one right after the other.
The sequence webhook, CEL, webhook works fine.

Thanks @fiunchinho for discovering the issue and creating the unit test to reproduce it!

# Steps to Reproduce the Problem

Unit test: https://github.com/tektoncd/triggers/pull/971/files

E2E: https://gist.github.com/b172b3f8c75aca27959befa332019bba

I tried both with `body.extensions`:
```
{"level":"info","ts":"2021-02-25T18:55:50.031Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = error evaluating cel expression: expression \"string(body.extensions.add_pr_body.pull_request_body.commits + 1.0)\" failed to evaluate: no such key: pull_request_body","knative.dev/controller":"eventlistener","/triggers-eventid":"nf6xt","/trigger":"chain-debug","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```
and `extensions`:
```
{"level":"info","ts":"2021-02-25T18:55:53.978Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = error evaluating cel expression: expression \"string(extensions.add_pr_body.pull_request_body.commits + 1.0)\" failed to evaluate: no such key: pull_request_body","knative.dev/controller":"eventlistener","/triggers-eventid":"hhsps","/trigger":"chain-debug","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```
But they seem to be both gone.

Putting a CEL in between the wehbooks works fine: https://gist.github.com/a236447aae9edddf740e327d089e151f
```

Andrea Frittoli  2 hours ago
The output I get from the task is
[print] === Step 1 ===
[print] body: {"action":"created","comment":{"author_association":"CONTRIB
[print] extensions: {}
[print] ===============
[print]
[print] === Step 2 ===
[print] body: {"action":"created","comment":{"author_association":"CONTRIB
[print] extensions: {"add_pr_body":{"pull_request_url":"https://api.github.com/r
[print] body.extensions: {"add_pr_body":{"pull_request_body":{"_links":{"comments":{"
[print] extensions.add_pr_body: {"pull_request_url":"https://api.github.com/repos/tektoncd/p
[print] ===============
[print]
[print] === Step 3 ===
[print] body: {"action":"created","comment":{"author_association":"CONTRIB
[print] extensions: {"add_pr_body":{"pull_request_url":"https://api.github.com/r
[print] body.extensions: {"add_pr_body":{"pull_request_url":"https://api.github.com/r
[print] extensions.add_pr_body: {"pull_request_url":"https://api.github.com/repos/tektoncd/p
[print] extensions.add_team_member: {"org_base_url":"https://api.github.com/orgs/tektoncd"}
[print] ===============
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.16.0
Pipeline version: v0.21.0
Triggers version: v0.11.2
Dashboard version: v0.14.0
```

**Comment by dibyom** [comment]
Thanks for writing this up. Looks like there is a (very ugly/hacky) workaround till we land a fix  -- add a CEL interceptor between the two webhook interceptors.

**Comment by dibyom** [comment]
One update from https://github.com/tektoncd/triggers/pull/971#discussion_r583248172. Not 100% sure but I think what is going on is:

```
yeah I think I get it....this happens if we are using nested json keys i.e. if both keys were added at the top-level instead of nested under add_pr_body I think this behavior would not happen.

I think the lines to blame is here: https://github.com/tektoncd/triggers/blob/master/pkg/sink/sink.go#L351

We are simply accounting for top level keys (like add_pr_body) and resetting its value to the one from request.Extensions. Instead we need to do some sort of a merge.

One way might be to marshal the body into a map[string]interface{}, then do a json merge, and then turn it back into a []byte.
```

**Comment by fiunchinho** [comment]
Using a CEL interceptor between the two webhook interceptors doesn't fix the issue for me. And if I understand the problem correctly, it shouldn't fix it. The code still uses `request.Extensions` when calling the second webhook, and `request.Extensions` is not aware of the extensions added by the first webhook.

**Comment by fiunchinho** [comment]
I pushed a new commit to my branch adding a CEL interceptor between the two webhooks to show that the unit test keeps failing.

**Comment by dibyom** [comment]
yeah looks like we'd have to fix how we merge request.Extensions and body.extensions.

**Comment by dibyom** [comment]
The workaround for now is if you have two webhook interceptors make sure they write to two different top level fields e.g. webookA can write to body.webhookA. and webhookB can write to body.webhookB.somefield.

**Comment by jmcshane** [comment]
I think given the new format for the v0.13 release, we can resolve this issue once migrating webhook endpoints to the new format is well documented. Since the extensions will need to be explicitly returned from the interceptor, triggers will no longer allow the body to be directly modified.

**Comment by jmcshane** [comment]
@dibyom @afrittoli I believe this issue is resolved now using custom interceptors (as long as the extensions field does not overlap). Maybe we change this issue to demonstrate @afrittoli use case with `add-pr-body` and `add-team-member` deployed as a custom interceptor.

**Comment by dibyom** [comment]
Do we still have this issue if two cluster interceptors write to the same top level extensions field (i.e. A writes extensions.foo and B also writes to extensions.foo)?

**Comment by jmcshane** [comment]
@dibyom what would be the expected behavior when you write data to the same extensions field? Right now, it would overwrite it when the second one wrote the same interceptor field.

**Comment by dibyom** [comment]
Overwriting actually sounds like a reasonable idea to me though some kind of merging could be an option too. Either way we should document the behavior in the docs. (I'll add this to the WG agenda, we can decide, and then update the docs).
